### ISSUE TITLE
Support for historical versions of reference trees (along with their corresponding root sequence)

### ISSUE THREAD

**Issue by elray1** [reichlab/variant-nowcast-hub#1]
We should be able to pull and operate with past versions of reference trees.  Note that much of the content of this issue was provided by John Huddleston.

My understanding is that we can pull the latest version of a reference tree that was available as of a given date using a command like the following:

```
curl https://nextstrain.org/nextclade/sars-cov-2@2023-10-26 \
  --header 'Accept: application/vnd.nextstrain.dataset.main+json' \
  --compressed > tree_2023-10-26.json
```

The key here is the `@2023-10-26` in the first line, which indicates that we want the latest tree that was available as of that date.

When we do this, we may need to also pull the root reference sequence. There are two cases here. For newer trees, that reference sequence will be stored directly in the tree's json file at `json["root_sequence"]["nuc"]`. That can be pulled out into a `.fasta` file as follows:

```
jq -r '.root_sequence .nuc' tree.json > root_sequence.fasta
```

For older trees, that reference root sequence will not be stored directly in the tree's json.  I think for our purposes, it's probably ok to ignore that -- we're doing this process going forward and don't need to look back to older trees.

**Comment by bsweger** [comment]
Closed by https://github.com/reichlab/variant-nowcast-hub/pull/5
(forgot to link that PR to this ticket)
