### ISSUE TITLE
Clarify hub instructions for modelers

### ISSUE THREAD

**Issue by bsweger** [reichlab/variant-nowcast-hub#120]
Based on the variant-nowcast hub's first two weeks of operation, we got some feedback from modelers about usability and where to write code.

Based on that feedback, we identified three potential, documentation-related improvements:

1. Update the README.md in`src` to clarify that it's not a place for modelers to work. Rather, anything in `src` is intended for hub admin use.
2. In the repo's main README.md, add a section about the how the repo is organized. Make sure the instructions for submitting to the hub are front and center.
3. Add an .Rproj file to the repo's root and clarify the purpose of having multiple .Rproj files

- Root: `variant-hub-modelers.Rproj`
- Src: `variant-hub-admin.Rproj`

**Comment by elray1** [comment]
Q: what kinds of things are modelers doing in the root of the hub repo?

**Comment by zkamvar** [comment]
> Q: what kinds of things do we anticipate that modelers will be doing in (the root of) the hub repo? I'm not typically in the position of running code from within a hub repo as a part of my modeling workflow.

I think they would be validating their models.

**Comment by zkamvar** [comment]
> Based on the variant-nowcast hub's first two weeks of operation, we got some feedback from modelers about usability and where to write code.
> 
> Based on that feedback, we identified three potential, documentation-related improvements:
> 
> 1. Update the README.md in`src` to clarify that it's not a place for modelers to work. Rather, anything in `src` is intended for hub admin use.
> 2. In the repo's main README.md, add a section about the how the repo is organized. Make sure the instructions for submitting to the hub are front and center.
> 3. Add an .Rproj file to the repo's root and clarify the purpose of having multiple .Rproj files
> 
> * Root: `variant-hub-modelers.Rproj`
> * Src: `variant-hub-admin.Rproj`

I will note that this provides the most ergonomic solution for people (as opposed to removing the Rproj files). Administrators can double-click on the `-admin` file to open the project in the `src/` folder when they want to construct some hub-wide functionality. Modelers can double-click on the `-modelers` file when they just want to submit something to the hub and don't want to be burdened by renv.
