### ISSUE TITLE
Error with finding custom validation function when running validations outside of repository root

### ISSUE THREAD

**Issue by elray1** [reichlab/variant-nowcast-hub#127]
This error was reported by Spencer:

```
> validate_submission(hub_path = '../variant-nowcast-hub',
+                     file_path = 'UGA-multicast/2024-10-23-UGA-multicast.parquet') -> sub_validation
Error in `purrr::map()`:
ℹ In index: 1.
ℹ With name: clade_prop_sum_one.
Caused by error in `file()`:
! cannot open the connection
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'src/validations/R/clade_prop_sum_one.R': No such file or directory
```

He confirmed that validations run OK if he runs them from within the hub repo root, specifying `hub_path = '.'`.  It seems like somewhere, we should be targeting the `clade_prop_sum_one.R` file relative to the `hub_path`, but we're just using that relative path directly.

**Comment by zkamvar** [comment]
Oops. that's my bad.

**Comment by zkamvar** [comment]
Tracking this in https://github.com/hubverse-org/hubValidations/issues/141

**Comment by nickreich** [comment]
Closing at it appears 141 was solved.
