### ISSUE TITLE
Dockerize the variant data pipeline

### ISSUE THREAD

**Issue by bsweger** [reichlab/variant-nowcast-hub#16]
For a few reasons, I propose that we "dockerize" our data pipeline sooner rather than later:

- Simplify the setup instructions (users wouldn't have to install various CLIs to make the pipeline work and deal with granting executions privileges to the unsigned software)
- Make it easier to run pipeline on other machines
- Sidestep potential cross-platform pathname issues when writing intermediate data files

What do you think, @elray1?

**Comment by elray1** [comment]
Sounds good to me! I :heart: docker

**Comment by bsweger** [comment]
This was resolved by #19 and #22
