### ISSUE TITLE
Automatically generate a round's clade list, save it, and submit a PR

### ISSUE THREAD

**Issue by bsweger** [reichlab/variant-nowcast-hub#26]
**Background**

When #25 is complete, this hub will have a function that generates a list of clades to be forecast for each modeling round.

The next step is to provided an automated way to schedule a run of this function prior to each round, and write the resulting .json file of clades to `variant-nowcast-hub/auxiliary-data/modeled-clades/YYYY-MM-DD.json`, where YYYY-MM-DD is the reference date of the upcoming round.

(note: we decided to save each reference date's clades in a separate file, rather than appending to a single, large file).

**Definition of done**

- [x] schedule the invocation of the `update_clades_list` function
- [x] write the output to the directory above
- [x] submit the update as PR to this repo, so it can be reviewed and merged by hub admins

**Comment by elray1** [comment]
since we now have a separate file for each week, with the reference date in the file name, do we need this to be json?  or could it literally just be a text file with e.g. comma-separated names of clades?

**Comment by bsweger** [comment]
> since we now have a separate file for each week, with the reference date in the file name, do we need this to be json? or could it literally just be a text file with e.g. comma-separated names of clades?

It can be whatever we want it to be!

**Comment by elray1** [comment]
i really struggle with pointless decisions like this, but i guess maybe making it json makes it easy to parse with standard tools
