### ISSUE TITLE
Use new append_round function when creating a new variant forecasting round

### ISSUE THREAD

**Issue by bsweger** [reichlab/variant-nowcast-hub#49]
[This PR](https://github.com/hubverse-org/hubAdmin/pull/43) adds a formal `append_round` function to `hubAdmin` 🥳 

Once it's ready, update this repo's `src/make_round_config.R` file to use `append_round` instead of the workaround code that's currently in place.

**Comment by zkamvar** [comment]
That PR was released with version 1.2.0: https://hubverse-org.github.io/hubAdmin/news/index.html#hubadmin-120

I will implement the change.
