### ISSUE TITLE
Create a custom Hub validation to check the sum of submitted values for a given state/location

### ISSUE THREAD

**Issue by bsweger** [reichlab/variant-nowcast-hub#55]

**Comment by nickreich** [comment]
Some more details on this are that we want to ensure that, for each modeling task (that is to say, for a given location and target_date), the clade proportion values that share a specific `output_type_id` sum to 1. This will require a custom validation function.

**Comment by zkamvar** [comment]
Related digging: it should be fairly straightforward. https://github.com/hubverse-org/hubValidations/issues/121

**Comment by nickreich** [comment]
Thanks, @zkamvar !

**Comment by zkamvar** [comment]
@nickreich or @bsweger can you provide some examples of valid and invalid data?

**Comment by bsweger** [comment]
I think @IsaacMacarthur is working on that: https://github.com/reichlab/variant-nowcast-hub/issues/56
