### ISSUE TITLE
Create example submission files

### ISSUE THREAD

**Issue by bsweger** [reichlab/variant-nowcast-hub#56]
Create a valid model-output file to serve as an example of what a submission to this hub will look like. Two purposes:

1. test validations (notably, the custom validation we're writing for this hub: https://github.com/reichlab/variant-nowcast-hub/issues/55)
2. show teams what a model-output file should look like

**Definition of done**

There should be two files: one good (where "good" = validates) and one "bad" (where bad = there is at least 1 model task where at least 1 set of samples sums to something other than one)

- [ ] single round (one file, one team)
- [ ] parquet format (this hub accepts parquet only)
- [ ] more than one target date and more than one location, but doesn't need to have them all
- [ ] 100 samples with correct sample ids
- [ ] location: auxiliary-data/example files
- [ ] add description of and link to the example files in the README in the root directory of the hub repo

**Comment by bsweger** [comment]
@nickreich to assign

**Comment by elray1** [comment]
It may be nice to create these examples using some simple, self-contained, and artificial process rather than using an actual prediction model.  For example, you might specify some Dirichlet distributions with arbitrary/hand-selected parameter values to use for each date.
