### ISSUE TITLE
pull run settings out into a config file and/or allow them to be specified as command line arguments

### ISSUE THREAD

**Issue by elray1** [reichlab/variant-nowcast-hub#7]
Looking at [these lines](https://github.com/reichlab/variant-nowcast-hub/blob/330080f85a081f11454ed79b9b1444b335d6d05f/data-pipeline/src/covid_variant_pipeline/assign_clades.py#L13-L21).

I think this would also address an issue where I was asked repeatedly if i wanted to overwrite or rename files when i downloaded some data.  I wasn't sure what path the file names i entered would be relative to, but i think it was one of these things.

**Comment by bsweger** [comment]
Addressed as part of this PR: This change was merged into the `variant-data-pipeline` as part of https://github.com/reichlab/variant-nowcast-hub/pull/15

(there's a new option for specifying the data directory)
