### ISSUE TITLE
test that validation fails when clade is missing

### ISSUE THREAD

**Issue by nickreich** [reichlab/variant-nowcast-hub#83]
This can be completed by submitting a file that is fully correct but in at least one model task is missing a required clade.

**Comment by zkamvar** [comment]
fixed with [hubValidations 0.7.0](https://github.com/hubverse-org/hubValidations/releases/tag/v0.7.0) as shown in https://github.com/reichlab/variant-nowcast-hub/pull/90#issuecomment-2391800200
